---
- hosts: linuxservers
  become: true

  tasks:
  - name: Create file
    ansible.builtin.file:
      path: /root/testfile.txt
      mode: 0644
      state: touch

  - name: Add line in file
    ansible.builtin.lineinfile:
      path: /root/testfile.txt
      line: Ansible was here...
